name: learning_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  collection: ^1.18.0
  dio: ^5.6.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  lottie: ^3.1.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/book.png
    - assets/pngtree-black-crown-icon-png-image_6549166.png
    - assets/image_demos_collections.png
    - assets/note.png
    - assets/lottie/themeChange.json
